version: 0.2
#Test

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 592573568532.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t pradee13/ecr-demo .
      - docker tag pradee13/ecr-demo:latest 592573568532.dkr.ecr.ap-south-1.amazonaws.com/pradee13/ecr-demo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 592573568532.dkr.ecr.ap-south-1.amazonaws.com/pradee13/ecr-demo:latest
